SYS_MSG: |
  SETTING:
  You are an expert in number theory, combinatorial optimization, and AI-driven mathematical discovery.
  Your task is to evolve and optimize a Python script to find a finite set of integers `U` that provides a new, world-record **lower bound** for the constant C₆.
  
  PROBLEM CONTEXT:
  Target: Find a finite set `U` of non-negative integers (containing 0) that **maximizes** the objective function:
  C6(U) = 1 + log(|U-U| / |U+U|) / log(2*max(U) + 1)
  
  This maximum value provides a tight lower bound for the constant C6.
  
  Current best known lower bound: C6 ≥ 1.158417281556896
  Goal: Find a set `U` that results in a C6 value greater than 1.158417281556896.
  
  # PROMPT-BLOCK-START

  METHOD:
  TODO

  OPTIMIZATION STRATEGIES TO CONSIDER:
  TODO

  # PROMPT-BLOCK-END
  
  PERFORMANCE METRICS:
  - c6_bound: Bound founded.
  - c6_ratio: c6_bound/1.158417281556896 (The primary objective is to MAXIMIZE this value - a value > 1 means a new record).
  - set_size: size of the set U.
  - max_val: max value in the set U.
  - eval_time: evaluation time of the main program.

  VALIDATION FRAMEWORK:
  - The evaluation script re-computes the C6 value using standard NumPy set operations and verifies the constraints on `U`.

CODEBASE_PATH: 'src/'
INIT_FILE_DATA: {filename: 'init_program.py', language: 'python'}
EVAL_FILE_NAME: 'evaluate.py'
EVAL_TIMEOUT: 360

MAX_MEM_BYTES: 5000000000
MEM_CHECK_INTERVAL_S: 0.1

EVOLVE_CONFIG: {fitness_key: 'c6_ratio',
                num_epochs: 200,ckpt: 5,max_size: 40,init_pop: 6,
                exploration_rate: 0.3, 
                selection_policy: 'roulette', selection_kwargs: {roulette_by_rank: True},
                early_stopping_rounds: 20,
                migration_interval: 40, migration_rate: 0.1,
                meta_prompting: True, num_inspirations: 3}

ENSEMBLE: [{model_name: 'GOOGLE_GEMINI-2.5-FLASH', temp: 0.7, top_p: 0.95, retries: 3, weight: 0.8, verify_ssl: False},
           {model_name: 'GOOGLE_GEMINI-2.5-PRO', temp: 0.7, top_p: 0.95, retries: 3, weight: 0.2, verify_ssl: False}]

SAMPLER_AUX_LM : {model_name: 'GOOGLE_GEMINI-2.5-FLASH', temp: 0.7, top_p: 0.95, retries: 3, weight: 0.8, verify_ssl: False}