name: evolve
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.11.10
  - aiosignal=1.2.0
  - annotated-types=0.6.0
  - anyio=4.7.0
  - asttokens=3.0.0
  - async-timeout=4.0.3
  - atk-1.0=2.36.0
  - attrs=24.3.0
  - blas=1.0
  - bottleneck=1.4.2
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - ca-certificates=2025.6.15
  - cairo=1.16.0
  - certifi=2025.6.15
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - click=8.1.8
  - comm=0.2.1
  - cuda-cudart=12.4.127
  - cuda-cudart_linux-64=12.4.127
  - cuda-nvrtc=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-version=12.4
  - cudnn=9.1.1.17
  - debugpy=1.8.11
  - decorator=5.1.1
  - deprecated=1.2.13
  - distro=1.9.0
  - executing=0.8.3
  - expat=2.7.1
  - filelock=3.17.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.10.4
  - fribidi=1.0.10
  - frozenlist=1.5.0
  - fsspec=2025.5.1
  - gdk-pixbuf=2.42.6
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.14
  - graphviz=2.49.0
  - greenlet=3.1.1
  - gtk2=2.24.33
  - gts=0.7.6
  - h11=0.16.0
  - harfbuzz=3.0.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - huggingface_hub=0.31.2
  - icu=68.2
  - idna=3.7
  - importlib-metadata=8.5.0
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=9.1.0
  - ipython_pygments_lexers=1.1.1
  - jbig=2.1
  - jedi=0.19.2
  - jinja2=3.1.6
  - jiter=0.6.1
  - jpeg=9e
  - jsonpatch=1.33
  - jsonpointer=2.1
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - langchain-openai=0.3.27
  - langsmith=0.3.45
  - ld_impl_linux-64=2.40
  - lerc=2.2.1
  - libabseil=20250127.0
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libcublas=12.4.5.8
  - libcufft=11.2.1.3
  - libcurand=10.3.5.147
  - libcusolver=11.6.1.9
  - libcusparse=12.3.1.170
  - libdeflate=1.7
  - libffi=3.4.4
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgd=2.3.3
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libglib=2.68.4
  - libgomp=15.1.0
  - libiconv=1.18
  - libltdl=2.4.3a
  - libmpdec=4.0.0
  - libnvjitlink=12.4.127
  - libpng=1.6.39
  - libprotobuf=5.29.3
  - librsvg=2.52.2
  - libsodium=1.0.18
  - libstdcxx=15.1.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.3.0
  - libtool=2.5.4
  - libtorch=2.5.1
  - libuuid=1.41.5
  - libuv=1.48.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxml2=2.9.12
  - litellm=1.74.0.post1
  - lz4-c=1.9.4
  - magma=2.7.1
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.1.0
  - nccl=2.21.5.1
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - numexpr=2.10.1
  - numpy=2.2.5
  - numpy-base=2.2.5
  - openai=1.91.0
  - openssl=3.5.1
  - opentelemetry-api=1.30.0
  - orjson=3.10.14
  - packaging=24.2
  - pandas=2.2.3
  - pango=1.48.10
  - parso=0.8.4
  - pcre=8.45
  - pexpect=4.9.0
  - pip=25.1
  - pip-system-certs=4.0
  - pixman=0.46.2
  - platformdirs=4.3.7
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - propcache=0.3.1
  - psutil=5.9.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pydantic=2.11.7
  - pydantic-core=2.33.2
  - pydot=4.0.1
  - pygments=2.19.1
  - pyparsing=3.2.3
  - pysocks=1.7.1
  - python=3.13.5
  - python-dateutil=2.9.0post0
  - python-dotenv=1.1.0
  - python-tzdata=2025.2
  - python_abi=3.13
  - pytorch=2.5.1
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - readline=8.2
  - referencing=0.30.2
  - regex=2024.11.6
  - requests=2.32.4
  - requests-toolbelt=1.0.0
  - rpds-py=0.22.3
  - setuptools=72.1.0
  - six=1.17.0
  - sleef=3.5.1
  - sniffio=1.3.0
  - sqlalchemy=2.0.39
  - sqlite=3.45.3
  - stack_data=0.2.0
  - sympy=1.13.3
  - tbb=2021.8.0
  - tenacity=9.0.0
  - tiktoken=0.9.0
  - tk=8.6.14
  - tokenizers=0.21.0
  - tornado=6.5.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing-inspection=0.4.0
  - typing_extensions=4.12.2
  - tzdata=2025b
  - urllib3=2.5.0
  - wcwidth=0.2.13
  - wheel=0.45.1
  - wrapt=1.17.0
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml=0.2.5
  - yarl=1.18.0
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - absl-py==2.3.1
      - alembic==1.16.4
      - bayesian-optimization==1.4.0
      - boto3==1.38.44
      - botocore==1.38.44
      - casadi==3.7.1
      - chex==0.1.91
      - clarabel==0.11.1
      - cloudpickle==3.1.1
      - cma==4.3.0
      - colorlog==6.9.0
      - contourpy==1.3.2
      - cvxpy==1.7.1
      - cycler==0.12.1
      - cython==3.1.2
      - dask==2025.7.0
      - dataclasses-json==0.6.7
      - deap==1.4.3
      - directsearch==1.0
      - fonttools==4.58.5
      - future==1.0.0
      - httpx-sse==0.4.1
      - hyperopt==0.2.7
      - immutabledict==4.2.1
      - iniconfig==2.1.0
      - jax==0.7.2
      - jaxlib==0.7.2
      - jmespath==1.0.1
      - joblib==1.5.1
      - kiwisolver==1.4.8
      - langchain==0.3.27
      - langchain-community==0.3.27
      - langchain-core==0.3.72
      - langchain-text-splitters==0.3.9
      - langgraph==0.5.4
      - langgraph-checkpoint==2.1.1
      - langgraph-prebuilt==0.5.2
      - langgraph-sdk==0.1.74
      - llvmlite==0.44.0
      - locket==1.0.0
      - mako==1.3.10
      - marshmallow==3.26.1
      - matplotlib==3.10.3
      - ml-dtypes==0.5.1
      - mypy-extensions==1.1.0
      - nevergrad==1.0.12
      - numba==0.61.2
      - opt-einsum==3.4.0
      - optax==0.2.6
      - optuna==4.4.0
      - ormsgpack==1.10.0
      - ortools==9.14.6206
      - osqp==1.0.4
      - partd==1.4.2
      - pillow==11.3.0
      - platypus==1.0
      - pluggy==1.6.0
      - ply==3.11
      - protobuf==6.31.1
      - py4j==0.10.9.9
      - pybullet==3.2.7
      - pydantic-settings==2.10.1
      - pymunk==7.1.0
      - pyomo==6.9.3
      - pytest==8.4.1
      - python-constraint==1.4.0
      - rtree==1.4.0
      - s3transfer==0.13.0
      - scikit-learn==1.7.1
      - scikit-opt==0.6.6
      - scipy==1.16.0
      - scs==3.2.7.post2
      - seaborn==0.13.2
      - shapely==2.1.1
      - sobol-seq==0.2.0
      - threadpoolctl==3.6.0
      - toolz==1.0.0
      - triangle==20250106
      - trimesh==4.7.3
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - xxhash==3.5.0
      
