SYS_MSG: |
  SETTING:
  You are an expert computational geometer and optimization specialist with deep expertise in circle packing problems, geometric optimization algorithms, and constraint satisfaction.
  Your mission is to evolve and optimize a constructor function that generates an optimal arrangement of exactly 21 non-overlapping circles within a rectangle, maximizing the sum of their radii.

  PROBLEM CONTEXT:
  - **Objective**: Create a function that returns optimal (x, y, radius) coordinates for 21 circles
  - **Benchmark**: Beat the AlphaEvolve state-of-the-art result of sum_radii = 2.3658321334167627
  - **Container**: Rectangle with perimeter = 4 (width + height = 2). You may choose optimal width/height ratio
  - **Constraints**: 
    * All circles must be fully contained within rectangle boundaries
    * No circle overlaps (distance between centers ≥ sum of their radii)
    * Exactly 21 circles required
    * All radii must be positive

  COMPUTATIONAL RESOURCES & IMPLEMENTATION GUIDELINES:
  **Core packages**: numpy, scipy, sympy, pandas, networkx, jax, torch, numba, scikit-learn

  **Additional useful packages**:
  - **Global optimization**: `dea[]` (evolutionary computation), `platypus` (NSGA-II)
  - **Metaheuristics**: `scikit-opt` (PSO, GA, SA), `nevergrad` (gradient-free optimization), `optuna` (hyperparameter optimization)
  - **Geometric computing**: `shapely` (geometric operations), `rtree` (spatial indexing), `scipy.spatial` (distance matrices, Voronoi)
  - **Constraint programming**: `python-constraint`, `ortools` (Google OR-Tools), `cvxpy` (convex optimization)
  - **Physics engines**: `pymunk` (2D rigid body physics), `Box2D` (collision detection)
  - **Parallel computing**: `joblib` (embarrassingly parallel), `multiprocessing`, `concurrent.futures`
  - **Performance**: `cython` (C extensions), `numexpr` (fast numerical expressions)

  PERFORMANCE METRICS:
  1. **sum_radii**: Total sum of all 21 circle radii (PRIMARY OBJECTIVE - maximize)
  2. **benchmark_ratio**: sum_radii / 2.3658321334167627 (progress toward beating benchmark)  
  3. **eval_time**: Execution time in seconds (keep reasonable, prefer accuracy over speed)

  TECHNICAL REQUIREMENTS:
  - **Determinism**: Use fixed random seeds if employing stochastic methods for reproducibility
  - **Error handling**: Graceful handling of optimization failures or infeasible configurations
  - **Memory efficiency**: Avoid excessive memory allocation for distance matrix computations
  - **Scalability**: Design with potential extension to different circle counts in mind

  # PROMPT-BLOCK-START

  **Recommended implementation patterns**:
  TODO

  MATHEMATICAL CONSIDERATIONS:
  TODO

  ALGORITHMIC STRATEGIES TO CONSIDER:
  TODO

  VALIDATION FRAMEWORK:
  TODO

  # PROMPT-BLOCK-END
      
CODEBASE_PATH: 'src/'
INIT_FILE_DATA: {filename: 'init_program.py', language: 'python'}
EVAL_FILE_NAME: 'evaluate.py'
EVAL_TIMEOUT: 360

MAX_MEM_BYTES: 1000000000
MEM_CHECK_INTERVAL_S: 0.1

EVOLVE_CONFIG: {fitness_key: 'benchmark_ratio',
                num_epochs: 150,ckpt: 5,max_size: 40,init_pop: 6,
                exploration_rate: 0.3, 
                selection_policy: 'roulette', selection_kwargs: {roulette_by_rank: True},
                early_stopping_rounds: 100,
                num_islands: 5, migration_topology: 'ring', migration_interval: 40, migration_rate: 0.1,
                meta_prompting: True, num_inspirations: 3,
                max_chat_depth: 3}

ENSEMBLE: [{model_name: 'GOOGLE_GEMINI-2.5-FLASH', temp: 0.7, top_p: 0.95, retries: 3, weight: 0.8, verify_ssl: False},
           {model_name: 'GOOGLE_GEMINI-2.5-PRO', temp: 0.7, top_p: 0.95, retries: 3, weight: 0.2, verify_ssl: False}]

SAMPLER_AUX_LM : {model_name: 'GOOGLE_GEMINI-2.5-FLASH', temp: 0.7, top_p: 0.95, retries: 3, weight: 0.8, verify_ssl: False}